/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pkg13.loginexamplewithfiles;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import loginexample.BusinessLogic.ServiceLogin;
import loginexample.Entities.Login;

/**
 *
 * @author jufeq
 */
public class InternalFrameRegisterUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameRegisterUser
     */
    public InternalFrameRegisterUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnRegisterUser = new javax.swing.JButton();
        lblRePassword = new javax.swing.JLabel();
        txtRePassword = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);

        lblUserName.setText("User name:");

        txtUserName.setToolTipText("User Name");
        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserNameFocusLost(evt);
            }
        });

        lblPassword.setText("Password:");

        txtPassword.setToolTipText("Password");

        btnRegisterUser.setText("Register");
        btnRegisterUser.setToolTipText("");
        btnRegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterUserActionPerformed(evt);
            }
        });

        lblRePassword.setText("Re-Password:");

        txtRePassword.setToolTipText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnRegisterUser, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegisterUser)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusLost
        if (txtUserName.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "The user name, is mandatory", "Register Alert", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            var serviceLogin = new ServiceLogin();
            if (serviceLogin.userExistInTheDataBase(txtUserName.getText().trim())) {
                JOptionPane.showMessageDialog(null, "The user name all ready exist, please try with a different user name", "Register Alert", JOptionPane.WARNING_MESSAGE);
                txtUserName.requestFocus(true);
                txtUserName.setText("");
            }
        } catch (IOException ex) {
            Logger.getLogger(InternalFrameRegisterUser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtUserNameFocusLost

    private void btnRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterUserActionPerformed
        //JOptionPane.showMessageDialog(null, "Invalid User and Password, please try again!", "Login alert", JOptionPane.ERROR_MESSAGE);
        if (txtUserName.getText().trim().equals("")
                || txtPassword.getText().trim().equals("")
                || txtRePassword.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "The user name, password and re-password are mandatory", "Register Alert", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!txtPassword.getText().trim().equals(txtRePassword.getText().trim())) {
            JOptionPane.showMessageDialog(null, "The password and re-password have different values", "Register Alert", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Login login = new Login(txtUserName.getText().trim(), txtPassword.getText().trim());
        try {
            var serviceLogin = new ServiceLogin();
            var registerResult = serviceLogin.registerUser(login);
            if (registerResult) {
                JOptionPane.showMessageDialog(null, "The user was registered", "Register Alert", JOptionPane.INFORMATION_MESSAGE);
                txtUserName.setText("");
                txtPassword.setText("");
                txtRePassword.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "The user name all ready exist, please try with a different user name", "Register Alert", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(InternalFrameRegisterUser.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "The user was not registered, please contact to the adminstrator", "Register Alert", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(InternalFrameRegisterUser.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "The user was not registered, please contact to the adminstrator", "Register Alert", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegisterUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRePassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
