/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pkg13.loginexamplewithfiles;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.UUID;
import javax.swing.table.TableRowSorter;
import logicexample.Repository.AccesorioRepository;
import loginexample.Entities.Accesorio;

/**
 *
 * @author jufeq
 */
public class InternalFrameAccessoriosV2 extends javax.swing.JInternalFrame {

    private ArrayList<Accesorio> lstAccesorios = new ArrayList<>();
    private AccesorioRepository respository;
    private TableRowSorter<ModelAccesoriosTable> tableSorter = new TableRowSorter<>();

    private int accesorioTempoNuevo = 1;

    /**
     * Creates new form InternalFrameAccessoriosV2
     */
    public InternalFrameAccessoriosV2() throws FileNotFoundException, Exception {
        initComponents();

        this.respository = new AccesorioRepository();
        lstAccesorios = this.respository.leerAccesorios();

        initialComponentsInternalFrameAccessoriosV2();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelTablev2 = new javax.swing.JScrollPane();
        tblAccesorios = new javax.swing.JTable();
        panelBotonesAcciones = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        tblAccesorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollPanelTablev2.setViewportView(tblAccesorios);

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");

        btnCancelar.setText("Cancelar");

        btnEliminar.setText("Eliminar");

        javax.swing.GroupLayout panelBotonesAccionesLayout = new javax.swing.GroupLayout(panelBotonesAcciones);
        panelBotonesAcciones.setLayout(panelBotonesAccionesLayout);
        panelBotonesAccionesLayout.setHorizontalGroup(
            panelBotonesAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBotonesAccionesLayout.setVerticalGroup(
            panelBotonesAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelTablev2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotonesAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanelTablev2, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addComponent(panelBotonesAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        UUID uuid = UUID.randomUUID();
        var accesorio = new Accesorio();

        accesorio.setCodigo(uuid.toString());
        accesorio.setCantidad(accesorioTempoNuevo);
        accesorio.setMaterial("Material" + accesorioTempoNuevo);
        accesorio.setNombre("Nombre Accesorio" + accesorioTempoNuevo);
        
        var accesorioModel = (ModelAccesoriosTable)this.tblAccesorios.getModel();
        accesorioModel.AddAccesorio(accesorio);
        
        accesorioTempoNuevo++;
    }//GEN-LAST:event_btnCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel panelBotonesAcciones;
    private javax.swing.JScrollPane scrollPanelTablev2;
    private javax.swing.JTable tblAccesorios;
    // End of variables declaration//GEN-END:variables

    private void initialComponentsInternalFrameAccessoriosV2() {
        var defaultModel = new ModelAccesoriosTable(this.lstAccesorios);

        tableSorter = new TableRowSorter<>(defaultModel);

        this.tblAccesorios.setRowSorter(tableSorter);
        this.tblAccesorios.setModel(defaultModel);
    }
}
