/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pkg13.loginexamplewithfiles;

import java.awt.BorderLayout;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import logicexample.Repository.AccesorioRepository;
import loginexample.Entities.Accesorio;

/**
 *
 * @author jufeq
 */
public class InternalFrameAccesorios extends javax.swing.JInternalFrame {

    private ArrayList<Accesorio> lstAccesorios = new ArrayList<>();
    private AccesorioRepository respository;

    /**
     * Creates new form InternalFrameAccesorios
     */
    public InternalFrameAccesorios() throws FileNotFoundException, Exception {
        initComponents();
        this.respository = new AccesorioRepository();
        lstAccesorios = this.respository.leerAccesorios();
        initialComponentsInternaFrameAccesorios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTableAccessorios = new javax.swing.JScrollPane();
        tblAccesorios = new javax.swing.JTable();
        panelBotonesAcciones = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        scrollTableAccessorios.setViewportView(tblAccesorios);

        tblAccesorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo Accesorio", "Nombre", "Disponible/Cant.", "Material"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollTableAccessorios.setViewportView(tblAccesorios);

        btnCrear.setText("Crear");

        btnModificar.setText("Modificar");

        btnEliminar.setText("Eliminar");

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout panelBotonesAccionesLayout = new javax.swing.GroupLayout(panelBotonesAcciones);
        panelBotonesAcciones.setLayout(panelBotonesAccionesLayout);
        panelBotonesAccionesLayout.setHorizontalGroup(
            panelBotonesAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBotonesAccionesLayout.setVerticalGroup(
            panelBotonesAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesAccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTableAccessorios, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotonesAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBotonesAcciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollTableAccessorios, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initialComponentsInternaFrameAccesorios() {
        String[][] contenidoTabla = new String[lstAccesorios.size()][4];

        for (int i = 0; i < lstAccesorios.size(); i++) {
            contenidoTabla[i][0] = lstAccesorios.get(i).getCodigo();
            contenidoTabla[i][1] = lstAccesorios.get(i).getNombre();
            contenidoTabla[i][2] = Integer.toString(lstAccesorios.get(i).getCantidad());
            contenidoTabla[i][3] = lstAccesorios.get(i).getMaterial();
        }

        String[] columns = {"Codigo Accesorio", "Nombre", "Disponible/Cant.", "Material"};
        DefaultTableModel defaultModel = new DefaultTableModel(contenidoTabla, columns) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tblAccesorios.setModel(defaultModel);
        
        /*JScrollPane scrollTable = new JScrollPane(tblAccesorios);
        this.setLayout(new BorderLayout());
        this.add(scrollTable);*/
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel panelBotonesAcciones;
    private javax.swing.JScrollPane scrollTableAccessorios;
    private javax.swing.JTable tblAccesorios;
    // End of variables declaration//GEN-END:variables
}
